### ISSUE TITLE
Vision Statement

### ISSUE THREAD

**Issue by CedricNdong** [CedricNdong/The-Vintage-Car-Community#1]

**Comment by YamanAlbakri** [comment]
Systemvision "it's more than Garage it's „The Vintage Garage Community " where the Store Keeper keep your Car (Safe , Clean , cool) , workshop  and the spare parts provider work  together to give you the best experience ,  The Vintage Garage Community Goal , to let the Customer reach experts & Garages in largest city in Germany with no effort "
Motorhead Team (31.08.2022)
