### ISSUE TITLE
Die Lagerhalter können Anfragen zu Reparaturen einstellen

### ISSUE THREAD

**Issue by assemnabill** [CedricNdong/The-Vintage-Car-Community#10]
Beschreibung:

StR.L.6 : Die Lagerhalter können Anfragen zu Reparaturen und Wartungsarbeiten an registrierte Werkstätten in der Nähe einstellen.

Todo:

- Use Case Diagramm erstellen
- Anforderungsspezifikationen beschreiben
- Sequenzdiagramm erstellen

**Comment by assemnabill** [comment]
@startuml
left to right direction
actor Lagerhalter as Lagerhalter

rectangle VintageCarCommunity {
  usecase "Als Lagerhalter Anmelden" as Anmelden
  usecase "Services für die Einlagerung anbieten" as Services
  usecase "Reparaturanfragen an Werkstätten einstellen" as Reparaturen

  (Services) .> (Anmelden) : include
  (Reparaturen) .> (Anmelden) : include

}

Lagerhalter --> Services
Lagerhalter --> Reparaturen

@enduml

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Kurzbeschreibung)
| Abschnitt | Beschreibung |
| --- | --- |
| Name |                 ...                     |
| Primärer Akteur |            ...             |
| Weitere Akteure |                 ...                     |
| Stakeholder-Ziel(e) |            ...             |
| Auslösendes Ereignis (Trigger) |                 ...                     |
| Beschreibung |            ...             |
| Beziehung zu anderen Use Cases |            ...             |

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Detailbeschreibung)
| Auslösendes Ereignis | Inhalt |
| --- | --- |
| Auslösendes Ereignis  |            ...             |
| Vorbedingung |                 ...                     |
| Nachbedingung |            ...             |
| Hauptszenario |                 ...                     |
| lternativszenarien |            ...             |
| Ausnahme szenarien |            ...             |
