### ISSUE TITLE
Die Einlagerer sollen Fahrzeug suchen können

### ISSUE THREAD

**Issue by CedricNdong** [CedricNdong/The-Vintage-Car-Community#11]
Beschreibung:

StR.E.1: Die Einlagerer sollen nach geeigneten Stellplätzen für ihr Fahrzeug suchen können. Die Suche
soll zunächst nur für deutsche Großstädte möglich sein.

Todo:

- Use Case Diagramm erstellen
- Anforderungsspezifikationen beschreiben
- Sequenzdiagramm erstellen

**Comment by ConstantinNshuti** [comment]
@startuml

left to right direction
skinparam packageStyle rectangle
actor Einlagerer 


rectangle Vintage-Garage-Community {
  Einlagerer--> (StellePlätze suchen)
  
  (StellePlätze suchen) .> (anmelden) : include
  (StellePlätze suchen) .> (deutsche Großstädte) : include
  
  
}
@enduml

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Kurzbeschreibung)
| Abschnitt | Beschreibung |
| --- | --- |
| Name |                 ...                     |
| Primärer Akteur |            ...             |
| Weitere Akteure |                 ...                     |
| Stakeholder-Ziel(e) |            ...             |
| Auslösendes Ereignis (Trigger) |                 ...                     |
| Beschreibung |            ...             |
| Beziehung zu anderen Use Cases |            ...             |

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Detailbeschreibung)
| Auslösendes Ereignis | Inhalt |
| --- | --- |
| Auslösendes Ereignis  |            ...             |
| Vorbedingung |                 ...                     |
| Nachbedingung |            ...             |
| Hauptszenario |                 ...                     |
| lternativszenarien |            ...             |
| Ausnahme szenarien |            ...             |
