### ISSUE TITLE
Die Lagerhalter können Termine mit der Werkstatt vereinbaren

### ISSUE THREAD

**Issue by assemnabill** [CedricNdong/The-Vintage-Car-Community#12]
Beschreibung:

StR.L.7 : Die Lagerhalter können Termine für Reparaturen oder Wartungsarbeiten mit der Werkstatt vereinbaren.

Todo:

- Use Case Diagramm erstellen
- Anforderungsspezifikationen beschreiben
- Sequenzdiagramm erstellen

**Comment by YamanAlbakri** [comment]
@startuml
left to right direction
skinparam packageStyle rectangle
actor Lagerhalter

rectangle VintageCarSystem {
usecase " Termin  mit werkstatt vereinbaren  " as Termin

Lagerhalter -- Termin


}

@enduml


![Image](https://user-images.githubusercontent.com/16928529/187672145-91aa4adc-2bd0-4e11-8caf-21e43ce34782.png)

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Kurzbeschreibung)
| Abschnitt | Beschreibung |
| --- | --- |
| Name |                 ...                     |
| Primärer Akteur |            ...             |
| Weitere Akteure |                 ...                     |
| Stakeholder-Ziel(e) |            ...             |
| Auslösendes Ereignis (Trigger) |                 ...                     |
| Beschreibung |            ...             |
| Beziehung zu anderen Use Cases |            ...             |
