### ISSUE TITLE
Registrieren von Spezialisierte Ersatzteilhändler

### ISSUE THREAD

**Issue by ConstantinNshuti** [CedricNdong/The-Vintage-Car-Community#13]
Beschreibung:

StR.EA.1: Spezialisierte Ersatzteilhändler für Oldtimer / Youngtimer können sich registrieren und
Informationen zum Unternehmen einstellen.

Todo:

- Use Case Diagramm erstellen
- Anforderungsspezifikationen beschreiben
- Sequenzdiagramm erstellen

**Comment by ConstantinNshuti** [comment]
@startuml

'Spezielle Ersatzhändler

left to right direction
skinparam packageStyle rectangle
actor Erzatzhändler as SE

rectangle Vintage-Garage-Community {

 usecase "Informationen einstellen" as InfoEin
 usecase "registrieren" as RG
usecase "spezialisieren" as SP
SE --> (InfoEin) 
(InfoEin) .> (RG) : include 
(InfoEin) .> (SP) : include

}


@enduml

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Kurzbeschreibung)
| Abschnitt | Beschreibung |
| --- | --- |
| Name |                 ...                     |
| Primärer Akteur |            ...             |
| Weitere Akteure |                 ...                     |
| Stakeholder-Ziel(e) |            ...             |
| Auslösendes Ereignis (Trigger) |                 ...                     |
| Beschreibung |            ...             |
| Beziehung zu anderen Use Cases |            ...             |
