### ISSUE TITLE
Werkstattinhaber registrieren und Informationen

### ISSUE THREAD

**Issue by YamanAlbakri** [CedricNdong/The-Vintage-Car-Community#15]
Beschreibung:

StR.W.1: Werkstattinhaber können sich registrieren und Informationen.
Todo:

1. Use Case Diagramm erstellen
2.Anforderungsspezifikationen beschreiben
3.Sequenzdiagramm erstellen

**Comment by YamanAlbakri** [comment]
@startuml


left to right direction
skinparam packageStyle rectangle
actor Werkstatt

rectangle The-Vintage-Garage-Community {
Werkstatt --> (Registrieren)

}
@enduml

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Kurzbeschreibung)
| Abschnitt | Beschreibung |
| --- | --- |
| Name |                 ...                     |
| Primärer Akteur |            ...             |
| Weitere Akteure |                 ...                     |
| Stakeholder-Ziel(e) |            ...             |
| Auslösendes Ereignis (Trigger) |                 ...                     |
| Beschreibung |            ...             |
| Beziehung zu anderen Use Cases |            ...             |

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Detailbeschreibung)
| Auslösendes Ereignis | Inhalt |
| --- | --- |
| Auslösendes Ereignis  |            ...             |
| Vorbedingung |                 ...                     |
| Nachbedingung |            ...             |
| Hauptszenario |                 ...                     |
| lternativszenarien |            ...             |
| Ausnahme szenarien |            ...             |
