### ISSUE TITLE
Die Einlagerer sollen Anfragen an Lagerhalter stellen können.

### ISSUE THREAD

**Issue by CedricNdong** [CedricNdong/The-Vintage-Car-Community#18]
Beschreibung:

StR.E.3: Die Einlagerer sollen Anfragen an Lagerhalter stellen können, um die Detailinformationen zum
Standort zu erhalten und ein Angebot anfordern zu können.

Todo:

- Use Case Diagramm erstellen
- Anforderungsspezifikationen beschreiben
- Sequenzdiagramm erstellen

**Comment by CedricNdong** [comment]
@startuml
left to right direction
actor Einlagerer
actor Lagerhalter
rectangle VintageCarCommunity {
usecase "Detailinformationen zum Standort anfragen" as Standort
usecase "Angebot anfordern" as Angebot
usecase "Detailinformationen zum Standort liefern" as Info

}
Einlagerer -- Standort
Einlagerer -- Angebot
Standort -- Lagerhalter
Info -- Lagerhalter
Info .> Angebot : << extend >>
@enduml

![image](http://www.plantuml.com/plantuml/svg/bP3DIWD13CVlynIXz_e0KfPAzI1K44JlSISp3SmaaCs07_ZkThJhAdZfQPXV_XyasydHlDKI2YK7Lp3E1uV8HgEpIi3HrU26fM0c8pk1VVyTiFYHT2bABWHFB8wPTcWxhRK9-okyXpRHY1F1wfeSkR0ajOezdGJUMeK7Hubg3YZ9C9Ei0ASVklYl9DEpVidK8jctxaJFg2bCQNRVIj8GFiAo8QpNI_TVF5VDuyv-NwA7_SikXjaBbx3P0BquIOHX2DlZssgvBoZ-UBU7o9WDQ_W4)

**Comment by ConstantinNshuti** [comment]
test

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Kurzbeschreibung)
| Abschnitt | Beschreibung |
| --- | --- |
| Name |                 ...                     |
| Primärer Akteur |            ...             |
| Weitere Akteure |                 ...                     |
| Stakeholder-Ziel(e) |            ...             |
| Auslösendes Ereignis (Trigger) |                 ...                     |
| Beschreibung |            ...             |
| Beziehung zu anderen Use Cases |            ...             |

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Detailbeschreibung)
| Auslösendes Ereignis | Inhalt |
| --- | --- |
| Auslösendes Ereignis  |            ...             |
| Vorbedingung |                 ...                     |
| Nachbedingung |            ...             |
| Hauptszenario |                 ...                     |
| lternativszenarien |            ...             |
| Ausnahme szenarien |            ...             |

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Detailbeschreibung)
| Auslösendes Ereignis | Inhalt |
| --- | --- |
| Auslösendes Ereignis  |            ...             |
| Vorbedingung |                 ...                     |
| Nachbedingung |            ...             |
| Hauptszenario |                 ...                     |
| lternativszenarien |            ...             |
| Ausnahme szenarien |            ...             |
