### ISSUE TITLE
Die Einlagerer können ein Angebot annehmen oder ablehnen.

### ISSUE THREAD

**Issue by CedricNdong** [CedricNdong/The-Vintage-Car-Community#21]
Beschreibung:

StR.E.4: Die Einlagerer können ein Angebot annehmen oder ablehnen.

Todo:

- Use Case Diagramm erstellen
- Anforderungsspezifikationen beschreiben
- Sequenzdiagramm erstellen

**Comment by YamanAlbakri** [comment]
@startuml
left to right direction
skinparam packageStyle rectangle
actor Einlagerer

rectangle VintageCarSystem {
usecase  "Angebot bekommen " as Angebot
usecase Annehmen
usecase Ablehen

Einlagerer -- Angebot
Annehmen .> Angebot : extends
Ablehen .> Angebot : extends

}

@enduml


![Image](https://user-images.githubusercontent.com/16928529/187695735-806302a8-3bcd-45b9-95eb-2ee19292389b.png)

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Kurzbeschreibung)
| Abschnitt | Beschreibung |
| --- | --- |
| Name |                 ...                     |
| Primärer Akteur |            ...             |
| Weitere Akteure |                 ...                     |
| Stakeholder-Ziel(e) |            ...             |
| Auslösendes Ereignis (Trigger) |                 ...                     |
| Beschreibung |            ...             |
| Beziehung zu anderen Use Cases |            ...             |

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Kurzbeschreibung)
| Abschnitt | Beschreibung |
| --- | --- |
| Name |                 ...                     |
| Primärer Akteur |            ...             |
| Weitere Akteure |                 ...                     |
| Stakeholder-Ziel(e) |            ...             |
| Auslösendes Ereignis (Trigger) |                 ...                     |
| Beschreibung |            ...             |
| Beziehung zu anderen Use Cases |            ...             |
