### ISSUE TITLE
Pauschalbetrag in Rechnung stellen 

### ISSUE THREAD

**Issue by ConstantinNshuti** [CedricNdong/The-Vintage-Car-Community#22]
Beschreibung:

StR.EA.2: Für jeden eingestellten Artikel (Ersatzteil- / Zubehör) wird dem Ersatzteilhändler vom
Community-Betreiber einen Pauschalbetrag in Rechnung gestellt.

Todo:

Use Case Diagramm erstellen
Anforderungsspezifikationen beschreiben
Sequenzdiagramm erstellen

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Kurzbeschreibung)
| Abschnitt | Beschreibung |
| --- | --- |
| Name |                 ...                     |
| Primärer Akteur |            ...             |
| Weitere Akteure |                 ...                     |
| Stakeholder-Ziel(e) |            ...             |
| Auslösendes Ereignis (Trigger) |                 ...                     |
| Beschreibung |            ...             |
| Beziehung zu anderen Use Cases |            ...             |

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Detailbeschreibung)
| Auslösendes Ereignis | Inhalt |
| --- | --- |
| Auslösendes Ereignis  |            ...             |
| Vorbedingung |                 ...                     |
| Nachbedingung |            ...             |
| Hauptszenario |                 ...                     |
| lternativszenarien |            ...             |
| Ausnahme szenarien |            ...             |
