### ISSUE TITLE
Ersatzteile anbieten und angebotenen Artikel wieder löschen

### ISSUE THREAD

**Issue by ConstantinNshuti** [CedricNdong/The-Vintage-Car-Community#28]
Beschreibung:

StR.EA.3: Ersatzteilhändler können verfügbare Ersatz- oder Zubehörteile anbieten und den angebotenen
Artikel ggf. wieder löschen.

Todo:

Use Case Diagramm erstellen
Anforderungsspezifikationen beschreiben
Sequenzdiagramm erstellen

**Comment by ConstantinNshuti** [comment]
@startuml
'Spezielle Ersatzhändler

left to right direction
skinparam packageStyle rectangle
actor Erzatzhändler as SE

rectangle Vintage-Garage-Community {

 usecase "Ersatz- oder Zubehörteile anbieten " as anbieten
 usecase "Ersatz- oder Zubehörteile löschen " as loschen
 
SE --> (anbieten)
SE --> (loschen) 

}
@enduml

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Kurzbeschreibung)
| Abschnitt | Beschreibung |
| --- | --- |
| Name |                 ...                     |
| Primärer Akteur |            ...             |
| Weitere Akteure |                 ...                     |
| Stakeholder-Ziel(e) |            ...             |
| Auslösendes Ereignis (Trigger) |                 ...                     |
| Beschreibung |            ...             |
| Beziehung zu anderen Use Cases |            ...             |

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Detailbeschreibung)
| Auslösendes Ereignis | Inhalt |
| --- | --- |
| Auslösendes Ereignis  |            ...             |
| Vorbedingung |                 ...                     |
| Nachbedingung |            ...             |
| Hauptszenario |                 ...                     |
| lternativszenarien |            ...             |
| Ausnahme szenarien |            ...             |
