### ISSUE TITLE
Die Einlagerer können sich Ersatz- und Zubehörteile suchen lassen.

### ISSUE THREAD

**Issue by CedricNdong** [CedricNdong/The-Vintage-Car-Community#29]
Beschreibung:

StR.E.5: Die Einlagerer können sich Ersatz- und Zubehörteile zu ihrem Fahrzeug anzeigen lassen, die von
Ersatzteilhändlern angeboten werden.

Todo:

- Use Case Diagramm erstellen
- Anforderungsspezifikationen beschreiben
- Sequenzdiagramm erstellen

**Comment by AbdullahAlhalak** [comment]
@startuml

left to right direction
skinparam packageStyle rectangle
actor Einlagerer
actor Ersatzteilhändlern
rectangle VintageCarSystem {

  Einlagerer --> (Erzatzteile bez. Zubehörteile zu dem Fahrzeug anzeigen lassen)
  
  (Ersatz/Zubehörteile werden von Ersatzteilhändlern angeboten )<-- Ersatzteilhändlern   

}

@enduml

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Kurzbeschreibung)
| Abschnitt | Beschreibung |
| --- | --- |
| Name |                 ...                     |
| Primärer Akteur |            ...             |
| Weitere Akteure |                 ...                     |
| Stakeholder-Ziel(e) |            ...             |
| Auslösendes Ereignis (Trigger) |                 ...                     |
| Beschreibung |            ...             |
| Beziehung zu anderen Use Cases |            ...             |

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Detailbeschreibung)
| Auslösendes Ereignis | Inhalt |
| --- | --- |
| Auslösendes Ereignis  |            ...             |
| Vorbedingung |                 ...                     |
| Nachbedingung |            ...             |
| Hauptszenario |                 ...                     |
| lternativszenarien |            ...             |
| Ausnahme szenarien |            ...             |
