### ISSUE TITLE
Die Einlagerer können Termine für das Entgegennehmen und die Rückgabe  vereinbaren.

### ISSUE THREAD

**Issue by CedricNdong** [CedricNdong/The-Vintage-Car-Community#32]
Beschreibung:

StR.E.6: Die Einlagerer können Termine für das Entgegennehmen und die Rückgabe ihres Fahrzeuges mit
dem Lagerhalter vereinbaren.

Todo:

- Use Case Diagramm erstellen
- Anforderungsspezifikationen beschreiben
- Sequenzdiagramm erstellen

**Comment by YamanAlbakri** [comment]
left to right direction
skinparam packageStyle rectangle
actor Einlagerer

rectangle The-Vintage-Garage-Community {
usecase (Terminen vereibaren)
usecase (Entgegennehmen Fahrzeug)
usecase (Rückgabe Fahrzeuges )
Einlagerer -- (Terminen vereibaren)
(Entgegennehmen Fahrzeug) .> (Terminen vereibaren) : extends
(Rückgabe Fahrzeuges ) .> (Terminen vereibaren) : extends

}
@enduml

**Comment by AbdullahAlhalak** [comment]
#32

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Kurzbeschreibung)
| Abschnitt | Beschreibung |
| --- | --- |
| Name |                 ...                     |
| Primärer Akteur |            ...             |
| Weitere Akteure |                 ...                     |
| Stakeholder-Ziel(e) |            ...             |
| Auslösendes Ereignis (Trigger) |                 ...                     |
| Beschreibung |            ...             |
| Beziehung zu anderen Use Cases |            ...             |

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Detailbeschreibung)
| Auslösendes Ereignis | Inhalt |
| --- | --- |
| Auslösendes Ereignis  |            ...             |
| Vorbedingung |                 ...                     |
| Nachbedingung |            ...             |
| Hauptszenario |                 ...                     |
| lternativszenarien |            ...             |
| Ausnahme szenarien |            ...             |
