### ISSUE TITLE
Reparaturanfragen von Lagerhaltern an Werkstattinhaber

### ISSUE THREAD

**Issue by YamanAlbakri** [CedricNdong/The-Vintage-Car-Community#33]
Beschreibung:

StR.W.3: Reparaturanfragen können von Lagerhaltern an Werkstattinhaber gestellt werden.
.

Todo:

- Use Case Diagramm erstellen
- Anforderungsspezifikationen beschreiben
- Sequenzdiagramm erstellen

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Kurzbeschreibung)
| Abschnitt | Beschreibung |
| --- | --- |
| Name |                 ...                     |
| Primärer Akteur |            ...             |
| Weitere Akteure |                 ...                     |
| Stakeholder-Ziel(e) |            ...             |
| Auslösendes Ereignis (Trigger) |                 ...                     |
| Beschreibung |            ...             |
| Beziehung zu anderen Use Cases |            ...             |

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Detailbeschreibung)
| Auslösendes Ereignis | Inhalt |
| --- | --- |
| Auslösendes Ereignis  |            ...             |
| Vorbedingung |                 ...                     |
| Nachbedingung |            ...             |
| Hauptszenario |                 ...                     |
| lternativszenarien |            ...             |
| Ausnahme szenarien |            ...             |
