### ISSUE TITLE
Ersatz- und Zubehörteile reservieren

### ISSUE THREAD

**Issue by ConstantinNshuti** [CedricNdong/The-Vintage-Car-Community#34]
Beschreibung:

StR.EA.4: Einlagerer können angebotene Ersatz- und Zubehörteile reservieren (Kauf, ggf. versenden, etc.)
wird extern durchgeführt.

Todo:

Use Case Diagramm erstellen
Anforderungsspezifikationen beschreiben
Sequenzdiagramm erstellen

**Comment by YamanAlbakri** [comment]
left to right direction
skinparam packageStyle rectangle
actor Ersatzteilanbieter

rectangle The-Vintage-Garage-Community {
usecase "Ersatz- und Zubehörteile reservieren" as reservieren
Ersatzteilanbieter -- reservieren
note " (Kauf, ggf. versenden, etc.) " as ErsatztN
reservieren .. ErsatztN
}
@enduml

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Kurzbeschreibung)
| Abschnitt | Beschreibung |
| --- | --- |
| Name |                 ...                     |
| Primärer Akteur |            ...             |
| Weitere Akteure |                 ...                     |
| Stakeholder-Ziel(e) |            ...             |
| Auslösendes Ereignis (Trigger) |                 ...                     |
| Beschreibung |            ...             |
| Beziehung zu anderen Use Cases |            ...             |

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Detailbeschreibung)
| Auslösendes Ereignis | Inhalt |
| --- | --- |
| Auslösendes Ereignis  |            ...             |
| Vorbedingung |                 ...                     |
| Nachbedingung |            ...             |
| Hauptszenario |                 ...                     |
| lternativszenarien |            ...             |
| Ausnahme szenarien |            ...             |
