### ISSUE TITLE
zusätzliches Angebot buchen @ Einlagerer

### ISSUE THREAD

**Issue by CedricNdong** [CedricNdong/The-Vintage-Car-Community#35]
Beschreibung:

 StR.E.7: Die Einlagerer können zusätzliche Services buchen, die vom Lagerhalter angeboten werden.

Todo:

- Use Case Diagramm erstellen
- Anforderungsspezifikationen beschreiben
- Sequenzdiagramm erstellen

**Comment by YamanAlbakri** [comment]
@startuml
left to right direction
skinparam packageStyle rectangle
actor Einlagerer

rectangle VintageCarSystem {
usecase  "zusätzliche Angebot buchen" as extraAngebot

note "kunde kann eine zusätzliche Services buchen, die vom Lagerhalter angeboten werden. ." as N2
(extraAngebot) .. N2

Einlagerer -- extraAngebot


}

@enduml


![Image](https://user-images.githubusercontent.com/16928529/187698421-c4a6bf8e-6b39-4a05-bb73-b266e5cf3eb5.png)

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Kurzbeschreibung)
| Abschnitt | Beschreibung |
| --- | --- |
| Name |                 ...                     |
| Primärer Akteur |            ...             |
| Weitere Akteure |                 ...                     |
| Stakeholder-Ziel(e) |            ...             |
| Auslösendes Ereignis (Trigger) |                 ...                     |
| Beschreibung |            ...             |
| Beziehung zu anderen Use Cases |            ...             |

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Detailbeschreibung)
| Auslösendes Ereignis | Inhalt |
| --- | --- |
| Auslösendes Ereignis  |            ...             |
| Vorbedingung |                 ...                     |
| Nachbedingung |            ...             |
| Hauptszenario |                 ...                     |
| lternativszenarien |            ...             |
| Ausnahme szenarien |            ...             |

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Detailbeschreibung)
| Auslösendes Ereignis | Inhalt |
| --- | --- |
| Auslösendes Ereignis  |            ...             |
| Vorbedingung |                 ...                     |
| Nachbedingung |            ...             |
| Hauptszenario |                 ...                     |
| lternativszenarien |            ...             |
| Ausnahme szenarien |            ...             |
