### ISSUE TITLE
Anwendungsfall Diagramm für Werkstatt fertigstellen

### ISSUE THREAD

**Issue by CedricNdong** [CedricNdong/The-Vintage-Car-Community#38]

**Comment by YamanAlbakri** [comment]
![Image](https://user-images.githubusercontent.com/16928529/187720108-0dd7bd4d-a920-4012-8bab-0c29c19b94fb.svg)

**Comment by assemnabill** [comment]
![](http://www.plantuml.com/plantuml/svg/RP3FQW913CRlUOhKKtkm3r1aiNXiJmhrKYXn_Lo3ind9P0KfVVUk8Blspt7c--KtysLUGZowDj5TxD62JxfniI1As0L7PjTc7xnLHnsQZSf1xIWkBH-bFaY3LPmJ-1ABDGb4KaTsNiCFlJpYUdxjKTzB2ZWH3JY_gKKVBSGNkMqxqpZp9r5NK4i1JmOFlsIBp6893Mp2KdY9Hakumc7Zn0f-qXezkL745Lr_F5k3JOwHM-BI8peNsxdqJXPxj_6z4aZfElw79Hh1wRGQ_R_kxs__-40tMxZ4_sW74JzMFmho4yzcQdNgjgWgeY-QmxPTcxu1)

**Comment by assemnabill** [comment]
@startuml
!theme vibrant

left to right direction
skinparam packageStyle rectangle

actor Werkstatt
actor Lagerhalter


rectangle VintageCarCommunity {

usecase "Werkstatt Konto anlegen" as Registrieren
usecase "Service anbieten" as W_Angebot
usecase "Reparaturanfragen an\nWerkstatt stellen" as Reparaturanfragen

Werkstatt --> W_Angebot
Werkstatt --> (Registrieren)
Lagerhalter -->Reparaturanfragen

W_Angebot .> Registrieren : <<include>>

}
@enduml
