### ISSUE TITLE
(Gesamt)Anwendungsfall Diagramm für Ersatzteilhändlern,Einlagerer, werkstatt,Lagerhalter

### ISSUE THREAD

**Issue by CedricNdong** [CedricNdong/The-Vintage-Car-Community#41]

**Comment by assemnabill** [comment]
@startuml
!theme vibrant
left to right direction

actor Lagerhalter as Lagerhalter
actor Einlagerer as Einlagerer
actor Werkstatt as Werkstatt
actor Erzatzhandler as Erzatzhandler
actor CommunityBetreiber as Admin


rectangle VintageCarCommunity {

usecase "Werkstatt Konto anlegen" as WKRegistrieren
usecase "Service anbieten" as W_Angebot
usecase "Lagehalter Konto anlegen" as LHRegisterieren
usecase "Services anbieten" as Services
usecase "Reparaturanfragen \nan Werkstätten einstellen" as Reparaturen
usecase "Kapazitäten angeben" as Capacities
usecase "Spezialgebiet\n angeben" as Fahrzeugsmarken
usecase "Informationen bereitstellen" as Info
usecase "Termin mit werkstatt vereinbaren " as LHTermin
usecase "Termin vereibaren" as ELTermin
usecase "Angebot machen" as AngebotM
usecase "Stellplatz suchen" as Platz
usecase "Anfragen an Lagerhalter" as Anfrage
usecase "Angebot anfordern" as AngebotAn
usecase "Anfragen beantworten" as Antwort
usecase "Angebot an-/ablehnen" as Action
usecase "Ersatzteile zu Fahrzeug suchen" as ETSuche
usecase "Zusätzliches Angebot buchen" as extraAngebot
usecase "Reparaturanfragen an\nWerkstatt stellen" as Reparaturanfragen
usecase "Ersatzteilhandler Konto anlegen" as EHRegisterieren
usecase "Pauschalbetrag in Rechnung stellen " as Pauschal
usecase "Ersatz- oder Zubehörteile anbieten " as anbieten
usecase "Ersatz- oder Zubehörteile löschen " as loschen
usecase "Ersatz- und Zubehörteile reservieren" as reservieren

Anfrage .> AngebotAn : <<extend>>
AngebotAn .> Action : <<include>>
W_Angebot .> WKRegistrieren : <<include>>


(WKRegistrieren) -[hidden]- (reservieren)
(WKRegistrieren) -[hidden]- (ELTermin)
(WKRegistrieren) -[hidden]- (Platz)
(WKRegistrieren) -[hidden]- (Anfrage)
(WKRegistrieren) -[hidden]- (ETSuche)
(WKRegistrieren) -[hidden]- (extraAngebot)
(WKRegistrieren) -[hidden]- (Pauschal)
(WKRegistrieren) -[hidden]- (Action)
(WKRegistrieren) -[hidden]- (anbieten)
(WKRegistrieren) -[hidden]- (AngebotAn)
(W_Angebot) -[hidden]- (WKRegistrieren)
(WKRegistrieren) -[hidden]- (loschen)
(WKRegistrieren) -[hidden]- (EHRegisterieren)

note left of ETSuche: "Sucherergebnisse enthalten \ndie Anschrift zusammen mit\ndessen Merkmalen und vor\nOrt angebotenen Services."
note left of (Platz) : "Die Suche ist\nnur für deutsche\nGroßstädte möglich"
note left of EHRegisterieren : "Samt Informationen\nzum Unternehmen"
note right of (Services) : z.B. Einschweißen des Fahrzeuges
note right of (LHRegisterieren) : "Samt Ort des Einlagerns,\nEinlagerungskosten,\nServicezeiten \nund Lagerbedingungen"

note right of Capacities : "Wie viele Plätze in welcher \nKategorie für Fahrzeuge\nverfügbar sind"
note right of Fahrzeugsmarken : "Auf welche Fahrzeugmarken\nLagerhalter spezialisiert ist"
note right of Info : "Fahrbereitschaft und\nWartungsstand des\njeweiligen Fahrzeuges"
note left of Anfrage: "Detailinformationen\nzum Standort anfragen"
note left of ELTermin: "Entgegennahme\noder Rückgabe \neines Fahrzeuges"
note left of extraAngebot : "Wird vom \nLagerhalter \nangeboten"
note left of Pauschal: "Wird dem \nErsatzteilhändlern gestellt"
}


Werkstatt --> W_Angebot

(Pauschal) <-- Admin

EHRegisterieren <-- Erzatzhandler 
(anbieten) <-- Erzatzhandler
(loschen) <-- Erzatzhandler

(reservieren) <-- Einlagerer
(ELTermin) <-- Einlagerer
(Platz) <-- Einlagerer
Anfrage <-- Einlagerer
ETSuche <-- Einlagerer
extraAngebot <-- Einlagerer

Lagerhalter --> Reparaturanfragen
Lagerhalter --> Antwort
Lagerhalter --> AngebotM
Lagerhalter --> LHRegisterieren
Lagerhalter --> Services
Lagerhalter --> Reparaturen
Lagerhalter --> Capacities
Lagerhalter --> Fahrzeugsmarken
Lagerhalter --> Info
Lagerhalter --> LHTermin
@enduml

**Comment by assemnabill** [comment]
![](http://www.plantuml.com/plantuml/svg/ZLVDRjl64x_pAURlKmByvTw3m8YJgX-mWmPnsW0fYs8fZiYjoQ4nExHR5dsMNF8CEUMc5-iEk2HNApdgITYPttnmllN2YM7fsoRxdzJO8jpRWWr9rk1MG3fWMzK2fMNSYEqeoyn6EePhKo7NfX5aC2v-1i3QKgF4aR-y0lizygqtBQBS-J79yc1ag0sLJH2F2G7qgclRdgpyzHA5qHOZyh9ihNSoKtSDLGt2BvR4ctvbU9Q0lxEiTxWn3k5iyUIg8-d0K8CLqXceOrTliR9Es28ZBJ8toFTsWnvRM9G9_FibLLXqik0qB258XyglVnYLuoFQtRxwYRhWtkATOICz6zgojqIGaw4GpTqd4IH0IqwmQOAIMIIsTsNkp61L0WcCVaD0l_ACZHKR6xsvmy6Qfa9rBT_7VsTg7h2lN6luDhRm8sqxReqM418Ko6WbTalv2_eTSci9MYlmC2VdNeMeC8m48NmZBfKRaHuOTA-lKrn84xHcKmTG8BsElbFTkskC3E3w6VT62R6c47X3SGie50BlqApHO9J8UvOlwOZM0Wt9GyU20Jk-ZgbSVMEA1ckQa6Eppi0rE--ue6qGXdvELFnfwtSt-bXaFlJEbyJGM4-T_OHYaS0_XKsWVwqg3UMqT5cSznHxrEFGzaSwQFrO1xqnlTluN1GeNYrOyfOsDVLK1VEXXYPSQdO5NOaC7_e2wzrdLY_cPW-Yq-i_YJQxpzxE9Dfq-ZWYsLEP238wRNiCnHo_iopK2PnVB5K4p-3vSvyOfFBY8bl8Yj6Q606MDarVeaVCGyiZad6N8BFioJx_AQn-hMrP8lssWYUHPq-_ZWmDUGgchJQSm8G8d425oZw1Yglv17GgcnEmCU0dGA6EJi7cJ2fkojaU914_eI_Ku0dKNeCfEgDE4FGsW6uxZOndSAQ_7i7UBRBE8I29paBKdLHQX4lozjXwkQ5tfcsHTBvx7deqmMlaszPeNseFt7USqqyiOCRlH4AQzz_vsRuJeL30U_6jHL1F4AppkgbdsEw-C9JOYtvkJjzpj_keox4KX7RtkTBfbYXCFXhqyqmhiBV4SXhw5ducZoAiMwHHIJYNrAt9N_LiE7zv3ckhCNX0k_k812Kk-n9TAdoT17vsGgDIud9GaVj_JjEZfyhTTbwAF37O7z2EMT30NYkgmD9IvR7gT69usVXgyRtLUn0Rz7jFLm629NZ0HdFjDLuPmQfZYsEKvw_9wHxPawh2C3XBPHgRv4vGKvVzDcYUkICpf_ZKTEFrOPr55irogbgJfFfKIRWpVATkHUlARo73ea5oOgZKEERq1_gCDBP2YjAHL4GOCrfXACQZ3olXHZLsB31jiaJ5DFIyZZL9XHv1fcun9rqNy7RtPNDRcG8X9xI4xd5duZar9ecrOrhOZrHEeNbIL-QbDycMgBBHljrz8bsu1DwuRaiVv7-oB5jM-6fr4LsxsJ8FuVbgDPtWIHifApdiisNu7NApCAAEyh9utGJ0yWzZsJ0f9yoAb1pocvB3U4l9SG9INXQdGCDqUE6aY73KfVJb94qPoMn8-VEWVDoNGw6eyLDMsgq7V6svbBXSvo-Gohvj_WK0)

**Comment by assemnabill** [comment]
```plantuml
@startuml
!theme vibrant
left to right direction

actor Lagerhalter as Lagerhalter
actor Einlagerer as Einlagerer
actor Werkstatt as Werkstatt
actor Erzatzteilhandler as Erzatzhandler

rectangle VintageCarCommunity {

usecase "Einlagerungsangebot\nanfordern" as AngebotAn
usecase "Einlagerungsangebot\nan-/ablehnen" as Action
usecase "Anfragen an Lagerhalter" as Anfrage
usecase "Zusätzliches Angebot buchen" as extraAngebot
usecase "Termin vereibaren" as ELTermin
usecase "Werkstatt Konto\n anlegen" as WKRegistrieren
usecase "Werkstattservice\n anbieten" as W_Angebot
usecase "Lagehalter Konto\n anlegen" as LHRegisterieren
usecase "Einlagerungsservices\n anbieten" as Services
usecase "Kapazitäten angeben" as Capacities
usecase "Spezialgebiet\n angeben" as Fahrzeugsmarken
usecase "Informationen bereitstellen" as Info
usecase "Termin mit werkstatt\n vereinbaren " as LHTermin
usecase "Einlagerungsangebot\nmachen" as AngebotM
usecase "Stellplatz suchen" as Platz
usecase "Ersatzteile zu Fahrzeug suchen" as ETSuche
usecase "Reparaturanfragen an\nWerkstatt stellen" as Reparaturanfragen
usecase "Ersatz- und Zubehörteile\nreservieren" as reservieren
usecase "Ersatzteilhandler Konto\nanlegen" as EHRegisterieren
usecase "Ersatz- oder Zubehörteile\nverwalten " as anbieten

Anfrage .> AngebotAn : <<extend>>
AngebotAn .> Action : <<include>>
W_Angebot .> WKRegistrieren : <<include>>


(WKRegistrieren) -[hidden]- (reservieren)
(WKRegistrieren) -[hidden]- (Platz)
(WKRegistrieren) -[hidden]- (ETSuche)
(WKRegistrieren) -[hidden]- (Action)
(WKRegistrieren) -[hidden]- (anbieten)
(WKRegistrieren) -[hidden]- (AngebotAn)
Services -[hidden]- extraAngebot
WKRegistrieren -[hidden]- Anfrage
(W_Angebot) -[hidden]- (WKRegistrieren)

(WKRegistrieren) -[hidden]- (EHRegisterieren)

note left of ETSuche: "Sucherergebnisse enthalten \ndie Anschrift zusammen mit\ndessen Merkmalen und vor\nOrt angebotenen Services."
note left of (Platz) : "Die Suche ist\nnur für deutsche\nGroßstädte möglich"
note left of EHRegisterieren : "Samt Informationen\nzum Unternehmen"
note right of (Services) : z.B. Einschweißen des Fahrzeuges
note right of (LHRegisterieren) : "Samt Ort des Einlagerns,\nEinlagerungskosten,\nServicezeiten \nund Lagerbedingungen"
note right of Capacities : "Wie viele Plätze in welcher \nKategorie für Fahrzeuge\nverfügbar sind"
note right of Fahrzeugsmarken : "Auf welche Fahrzeugmarken\nLagerhalter spezialisiert ist"
note right of Info : "Fahrbereitschaft und\nWartungsstand des\njeweiligen Fahrzeuges"
note left of Anfrage: "Detailinformationen\nzum Standort anfragen"
note left of ELTermin: "Entgegennahme\noder Rückgabe \neines Fahrzeuges"

}

(reservieren) -- Einlagerer
(ELTermin) -- Einlagerer
(Platz) -- Einlagerer
Anfrage -- Einlagerer
ETSuche -- Einlagerer
extraAngebot -- Einlagerer

Lagerhalter -- Anfrage
Lagerhalter -- extraAngebot
Lagerhalter -- Reparaturanfragen
Lagerhalter -- AngebotM
Lagerhalter -- LHRegisterieren
Lagerhalter -- Services
Lagerhalter -- Capacities
Lagerhalter -- Fahrzeugsmarken
Lagerhalter -- Info
Lagerhalter -- LHTermin
Lagerhalter -- ELTermin

Werkstatt -- W_Angebot
Werkstatt -- Reparaturanfragen
Werkstatt -- LHTermin

EHRegisterieren -- Erzatzhandler
(anbieten) -- Erzatzhandler
@enduml
```

**Comment by assemnabill** [comment]
![](http://www.plantuml.com/plantuml/svg/XLRDRjms4BxhAQO-EK3NlGT143TrVs07BUAq1b8L1INDIgofaK6Ex5P5doMNFaDEkUsBTSYbH2qtw9u4pNppm_b_vLXP7djJVC4TzWYFkhAAk32uPU01h6uxXaPRh5aFL1Igvi72ZMhHTiemMb1k_Hi1LvgC9-xvwI-oxz3UYsbcuQQVMTPEYYT6RJf5ZOag0Z4IYiBxewWr2BzeOj7zMjdNGz-FfFal-BieHeUrSWXdi-sHMYSIM0rSagBjO1kqTEPrN-x9btHIQlELgWnsX54m12L9NTBMYXI1edLC0ZRo4lZzw7R_ycHqtU7Y0rHZtKNj-2TR5Ub9x1tQNXCyeaLTAHknLpTxUiAb45yFn4FfdJBOHlpTzLjijMEhqUBdf1pQHrrZ4AiqyYpt-v53_g6n53vdwURxlILScyf37AsvtDnjf2UfQ_MW9iqIEIG8cOdGryAeDUir-FO19wrCYrvbUOZ_LdLsmh5rlRBtQxz-yBNHAvzP9AXydDan6XC5FVye7RrcU9fZLyRqKCWFn304vAaIwzMI_XZeDwldU2yUZE89N2gJdpnXfTQws3q8qxWySornzUxM_oIPj_YWhEBHgbJ09QKAMZ__29kRti183RmVA-ns7srmf2IB8SKurslwp-LJuwU2MjVJLLvFkVMXGPkRbtGyASCn6KkD5KNiIhXucQO0F8SNBwJva9gNBuk5B9ZOy06WgJPZWu9OUa8GMMDboA8uF-G_WysldMuQfDysSBuAohF_HuQSdy34B9z0xLzq0XJZTGesXqfmS-Ek-8VpB8jJWYs3ydo9ww6Lp8CJCStAHU0qC4BORyDsReNdS1Q-5grO9EqS0X9t-vefgT4eVhcwirhafj6fliVGzS93GHEyaMxfbK4AvVyus99-j0oniv6GbcbsSNReH4mdY1VVQ8JW2MWdkccqiDrzij3Wo4x89NrdXzq79mEmOOH-zx7r2oHJc3qQ_FDKpt0msagQnXv-9a4HTZrILE9N_jwjsL_lsNJnzONVu-B44-hT1oJnAKrHTBdmJHRunGaVbGRJKK3kovBMm_1-42aIOhG_eTvdmGSshDKA6qsjO8-TJcl06xpJ_gH1Wp8b_R95q0HFQ7ogHU6rOcm7gp44EJqc30mXjPMou3GrkPLiUNXJb-CsQbwuUsP9wsl9xLUITXej-oJdgdsEl3wl92wVkbDRzcKbCrbP3WkJ5JK-Z2NzWP8GerkaLJQoWeWzvGiCMGdwk11klSR1CinpFLCnNnYYuuguHK6GwdeiAGpSjxjFzNshAfImeYPq1yuK_nJ5mNY3pMPz5PxFsdD6R8sC6f-JKMClPzJrrCbOnJenmefgS_9QGyuxseOP86tnZ9wrHywUMo-Zf_BEENb9vcnVLZajtYGvDXsJHJe1XBpCuqFoSGWIUssaoAQICBEhFksPOzuhf6RipNy0)
