### ISSUE TITLE
Die Lagerhalter können Services für die Einlagerung von Fahrzeugen anbieten

### ISSUE THREAD

**Issue by assemnabill** [CedricNdong/The-Vintage-Car-Community#6]
Beschreibung:

StR.L.2: Die Lagerhalter sollen verschiedene Services für die Einlagerung von Fahrzeugen anbieten können, z.B. Einschweißen des Fahrzeuges in Folie, Glasbox etc.

Todo:

- Use Case Diagramm erstellen
- Anforderungsspezifikationen beschreiben
- Sequenzdiagramm erstellen

**Comment by assemnabill** [comment]
```plantuml
@startuml
left to right direction
actor Lagerhalter as LH

rectangle VintageCarCommunity {
  usecase "Anmelden" as Anmelden
  usecase "Services anbieten" as Services

  (Services) .> (Anmelden) : include

}

LH --> Services

@enduml
```

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Kurzbeschreibung)
| Abschnitt | Beschreibung |
| --- | --- |
| Name |                 ...                     |
| Primärer Akteur |            ...             |
| Weitere Akteure |                 ...                     |
| Stakeholder-Ziel(e) |            ...             |
| Auslösendes Ereignis (Trigger) |                 ...                     |
| Beschreibung |            ...             |
| Beziehung zu anderen Use Cases |            ...             |

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Detailbeschreibung)
| Auslösendes Ereignis | Inhalt |
| --- | --- |
| Auslösendes Ereignis  |            ...             |
| Vorbedingung |                 ...                     |
| Nachbedingung |            ...             |
| Hauptszenario |                 ...                     |
| lternativszenarien |            ...             |
| Ausnahme szenarien |            ...             |
