### ISSUE TITLE
Die Lagerhalter sollen Verfügbarkeit angeben können

### ISSUE THREAD

**Issue by assemnabill** [CedricNdong/The-Vintage-Car-Community#7]
Beschreibung:

StR.L.3: Die Lagerhalter sollen auch angeben können, wie viele Plätze in welcher Kategorie für Fahrzeuge momentan zur Verfügung stehen.

Todo:

- Use Case Diagramm erstellen
- Anforderungsspezifikationen beschreiben
- Sequenzdiagramm erstellen

**Comment by CedricNdong** [comment]
@startuml
left to right direction
actor Lagerhalter
rectangle VintageCarCommunity {
  usecase "Anzahl von verfügbaren Plätzen in Kategorie bestimmen" as Plätze

}
Lagerhalter --> Plätze

@enduml



![Image](http://www.plantuml.com/plantuml/svg/JSunJe1048NXVaxnGiyL38PI2olx0OPbajtPP7OW4UDjF8OT5rCAe_NtalVJq88zzf8fong82jUq1HPrcKEh4SzH7S-Sn3VE8KwtiAKiU5MB7nZPnrhARXflU2TWRp9p4tIFTlAMSLJ38RvUNsbY5yDBlZxZ58CQdZWaLLV192sq5B4Et7utH1_qxnrz__17WzXonty3)

**Comment by ConstantinNshuti** [comment]
#7

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Kurzbeschreibung)
| Abschnitt | Beschreibung |
| --- | --- |
| Name |                 ...                     |
| Primärer Akteur |            ...             |
| Weitere Akteure |                 ...                     |
| Stakeholder-Ziel(e) |            ...             |
| Auslösendes Ereignis (Trigger) |                 ...                     |
| Beschreibung |            ...             |
| Beziehung zu anderen Use Cases |            ...             |

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Detailbeschreibung)
| Auslösendes Ereignis | Inhalt |
| --- | --- |
| Auslösendes Ereignis  |            ...             |
| Vorbedingung |                 ...                     |
| Nachbedingung |            ...             |
| Hauptszenario |                 ...                     |
| lternativszenarien |            ...             |
| Ausnahme szenarien |            ...             |

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Detailbeschreibung)
| Auslösendes Ereignis | Inhalt |
| --- | --- |
| Auslösendes Ereignis  |            ...             |
| Vorbedingung |                 ...                     |
| Nachbedingung |            ...             |
| Hauptszenario |                 ...                     |
| lternativszenarien |            ...             |
| Ausnahme szenarien |            ...             |

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Detailbeschreibung)
| Auslösendes Ereignis | Inhalt |
| --- | --- |
| Auslösendes Ereignis  |            ...             |
| Vorbedingung |                 ...                     |
| Nachbedingung |            ...             |
| Hauptszenario |                 ...                     |
| lternativszenarien |            ...             |
| Ausnahme szenarien |            ...             |
