### ISSUE TITLE
Die Lagerhalter können Fahrzeugmarken angeben

### ISSUE THREAD

**Issue by assemnabill** [CedricNdong/The-Vintage-Car-Community#8]
Beschreibung:

StR.L.4: Die Lagerhalter sollen auch angegeben können, auf welche Fahrzeugmarken sie spezialisiert sind, hierzu soll das System eine Liste gängiger Marken vorhalten.

Todo:

- Use Case Diagramm erstellen
- Anforderungsspezifikationen beschreiben
- Sequenzdiagramm erstellen

**Comment by YamanAlbakri** [comment]
@startuml
left to right direction
skinparam packageStyle rectangle
actor Lagerhalter

rectangle VintageCarSystem {
usecase "Spezialgebiet (Fahrzeugsmarken) angeben" as Fahrzeugsmarken

Lagerhalter -- Fahrzeugsmarken

}

@enduml


![Image](https://user-images.githubusercontent.com/16928529/187669012-ce6a2c29-15e1-4d9f-b956-864f28e50629.png)

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Kurzbeschreibung)
| Abschnitt | Beschreibung |
| --- | --- |
| Name |                 ...                     |
| Primärer Akteur |            ...             |
| Weitere Akteure |                 ...                     |
| Stakeholder-Ziel(e) |            ...             |
| Auslösendes Ereignis (Trigger) |                 ...                     |
| Beschreibung |            ...             |
| Beziehung zu anderen Use Cases |            ...             |

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Detailbeschreibung)
| Auslösendes Ereignis | Inhalt |
| --- | --- |
| Auslösendes Ereignis  |            ...             |
| Vorbedingung |                 ...                     |
| Nachbedingung |            ...             |
| Hauptszenario |                 ...                     |
| lternativszenarien |            ...             |
| Ausnahme szenarien |            ...             |
