### ISSUE TITLE
Die Lagerhalter sollen Fahrbereitschaft und den Wartungsstand bereitstellen

### ISSUE THREAD

**Issue by assemnabill** [CedricNdong/The-Vintage-Car-Community#9]
Beschreibung:

StR.L.5 : Die Lagerhalter sollen aktuelle Informationen über die Fahrbereitschaft und den Wartungsstand des jeweiligen Fahrzeuges bereitstellen.

Todo:

- Use Case Diagramm erstellen
- Anforderungsspezifikationen beschreiben
- Sequenzdiagramm erstellen

**Comment by AbdullahAlhalak** [comment]
@startuml

left to right direction
skinparam packageStyle rectangle
actor Lagerhalter

rectangle Verfeugbarkeit {

  Lagerhalter --> (Fahrbereitschaft)
  
  
  Lagerhalter --> (Wartungsstand)
  

   
}


@enduml

**Comment by assemnabill** [comment]
@AbdullahAlhalak Nach `rectangle` kommt das System und nicht der Anwendungsfall. Also `VintageCarCommunity`

**Comment by assemnabill** [comment]
Bitte Anwendungsfälle deklarieren und nicht direkt als Text angeben, Bsp: `usecase "Beschreibung" as UC1`

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Kurzbeschreibung)
| Abschnitt | Beschreibung |
| --- | --- |
| Name |                 ...                     |
| Primärer Akteur |            ...             |
| Weitere Akteure |                 ...                     |
| Stakeholder-Ziel(e) |            ...             |
| Auslösendes Ereignis (Trigger) |                 ...                     |
| Beschreibung |            ...             |
| Beziehung zu anderen Use Cases |            ...             |

**Comment by ConstantinNshuti** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Kurzbeschreibung)
| Abschnitt | Beschreibung |
| --- | --- |
| Name |                 Wartungsstand                     |
| Primärer Akteur |            Lagerhalter             |
| Weitere Akteure |                 ...                     |
| Stakeholder-Ziel(e) |             Informationen über die Fahrbereitschaft des jeweiligen Fahrzeuges zur Verfügung stellen            |
| Auslösendes Ereignis (Trigger) |                 ...                     |
| Beschreibung |            aktuelle Informationen über  den Wartungsstand des jeweiligen Fahrzeuges sollen bereitgestellt             |
| Beziehung zu anderen Use Cases |            Informationen am Bildschirm anzeigen lassen             |

**Comment by CedricNdong** [comment]
## Teil : Anforderungsspezifikationen beschreiben (Detailbeschreibung)
| Auslösendes Ereignis | Inhalt |
| --- | --- |
| Auslösendes Ereignis  |            ...             |
| Vorbedingung |                 ...                     |
| Nachbedingung |            ...             |
| Hauptszenario |                 ...                     |
| lternativszenarien |            ...             |
| Ausnahme szenarien |            ...             |
